export const DROPDOWN_CATEGORIES = {
  platform: "Firearm Platform",
  caliber: "Caliber",
  accessory_type: "Accessory Type",
  ammo_type: "Ammo Type",
  ammo_manufacturer: "Ammo Manufacturer",
  maintenance_type: "Maintenance Type",
  malfunction_type: "Malfunction Type",
  zero_distance: "Zero Distance",
  range_location: "Range Location",
  weather: "Weather Conditions",
  position: "Shooting Position",
} as const;

export type DropdownCategory = keyof typeof DROPDOWN_CATEGORIES;

export const DROPDOWN_USED_IN: Record<DropdownCategory, string> = {
  platform: "Armory / firearm and accessory forms",
  caliber: "Armory, Ammo, and Update Rounds Fired",
  accessory_type: "Armory / accessories",
  ammo_type: "Ammo / purchases",
  ammo_manufacturer: "Ammo / purchases",
  maintenance_type: "Armory / maintenance log (Cleaning is always available and resets the round counter)",
  malfunction_type: "Armory / malfunction log",
  zero_distance: "Armory / zero log",
  range_location: "Log a Range Session",
  weather: "Log a Range Session",
  position: "Course of Fire Builder / Position column",
};


export const DEFAULT_OPTIONS: Record<DropdownCategory, string[]> = {
  platform: [
    "Pistol (Semi-Auto)",
    "Revolver",
    "Rifle (Semi-Auto)",
    "Rifle (Bolt-Action)",
    "Rifle (Lever-Action)",
    "Rifle (Pump-Action)",
    "AR Pistol",
    "SBR (Short-Barreled Rifle)",
    "Shotgun (Pump)",
    "Shotgun (Semi-Auto)",
    "Shotgun (Break-Action / Double)",
  ],
  caliber: [
    ".22 LR",
    "9mm",
    ".380 ACP",
    ".40 S&W",
    ".45 ACP",
    ".357 Magnum",
    ".38 Special",
    "5.56mm / .223",
    "7.62x39mm",
    "7.62x51mm / .308",
    "300 Blackout",
    "6.5 Creedmoor",
    "10mm Auto",
    "12 Gauge",
    "20 Gauge",
    ".410 Bore",
  ],
  accessory_type: [
    "Optic / Red Dot",
    "Scope",
    "Suppressor",
    "Magazine",
    "Sling",
    "Weapon Light",
    "Laser",
    "Grip",
    "Stock / Brace",
    "Rail / Mount",
    "Trigger",
  ],
  ammo_type: [
    "FMJ",
    "JHP (Hollow Point)",
    "Soft Point",
    "Frangible",
    "Wadcutter",
    "Tracer",
    "Blank",
    "Buckshot",
    "Birdshot",
    "Slug",
  ],
  ammo_manufacturer: [
    "Federal",
    "Winchester",
    "Remington",
    "Hornady",
    "CCI",
    "Speer",
    "PMC",
    "Fiocchi",
    "Sellier & Bellot",
    "Blazer",
    "Magtech",
    "Aguila",
  ],
  maintenance_type: ["Cleaning", "Lubrication", "Inspection", "Parts Replacement", "Repair", "Gunsmith Service"],
  malfunction_type: [
    "Failure to Feed",
    "Failure to Eject",
    "Stovepipe",
    "Double Feed",
    "Failure to Extract",
    "Failure to Fire / Light Strike",
    "Failure to Lock Back",
    "Out of Battery",
    "Squib",
    "Magazine Issue",
  ],
  zero_distance: ["7 yd", "15 yd", "25 yd", "36 yd", "50 yd", "100 yd", "200 yd", "300 yd"],
  range_location: [],
  weather: ["Clear", "Partly Cloudy", "Overcast", "Rain", "Windy", "Hot", "Cold", "Low Light / Night"],
  position: ["Standing", "Kneeling", "Prone", "Sitting", "Barricade", "Draw", "Low Ready", "High Ready", "Compressed Ready"],
};
