export const DROPDOWN_CATEGORIES = {
  platform: "Firearm Platform",
  caliber: "Caliber",
  accessory_type: "Accessory Type",
  ammo_type: "Ammo Type",
} as const;

export type DropdownCategory = keyof typeof DROPDOWN_CATEGORIES;

export const DEFAULT_OPTIONS: Record<DropdownCategory, string[]> = {
  platform: [
    "Pistol (Semi-Auto)",
    "Revolver",
    "Rifle (Semi-Auto)",
    "Rifle (Bolt-Action)",
    "Rifle (Lever-Action)",
    "Rifle (Pump-Action)",
    "AR Pistol",
    "SBR (Short-Barreled Rifle)",
    "Shotgun (Pump)",
    "Shotgun (Semi-Auto)",
    "Shotgun (Break-Action / Double)",
  ],
  caliber: [
    ".22 LR",
    "9mm",
    ".380 ACP",
    ".40 S&W",
    ".45 ACP",
    ".357 Magnum",
    ".38 Special",
    "5.56mm / .223",
    "7.62x39mm",
    "7.62x51mm / .308",
    "300 Blackout",
    "6.5 Creedmoor",
    "10mm Auto",
    "12 Gauge",
    "20 Gauge",
    ".410 Bore",
  ],
  accessory_type: [
    "Optic / Red Dot",
    "Scope",
    "Suppressor",
    "Magazine",
    "Sling",
    "Weapon Light",
    "Laser",
    "Grip",
    "Stock / Brace",
    "Rail / Mount",
    "Trigger",
  ],
  ammo_type: [
    "FMJ",
    "JHP (Hollow Point)",
    "Soft Point",
    "Frangible",
    "Wadcutter",
    "Tracer",
    "Blank",
    "Buckshot",
    "Birdshot",
    "Slug",
  ],
};
